- platform: darksky
  api_key: !secret dark_sky_key

  monitored_conditions:
#    - summary
#    - precip_type
    - precip_intensity
    - temperature
#    - dew_point
#    - wind_speed
#    - wind_bearing
    - cloud_cover
    - humidity
#    - nearest_storm_distance
    - minutely_summary
#    - pressure
#    - visibility
#    - ozone

- platform: nest
  monitored_conditions:
     - 'temperature'
     - 'target'
     - 'humidity'
     - 'operation_mode'
     - 'last_connection'
     - 'co_status'
     - 'smoke_status'

- platform: moon

- platform: yr