- alias: Turn off humidifier in the morning
  trigger:
    platform: time
    after: '07:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.switch_02

- alias: Turn on humidifier at night
  trigger:
    platform: time
    after: '19:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.switch_02

- alias: Turn off most things at night
  trigger:
    platform: time
    after: '03:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.switch_01 # Kitchen Audio
    - service: switch.turn_off
      entity_id: switch.switch_03 # Bedroom Entertainment Center
    - service: switch.turn_off
      entity_id: switch.switch_04 # Front Room Audio
    - service: switch.turn_off
      entity_id: switch.switch_05 # Den Entertainment Center